title: Aneesh Indavarapu
# author:
#   name: indavarapuaneesh
description: > # this means to ignore newlines until "show_excerpts:"

show_excerpts: false # set to true to show excerpts on the homepage

minima: 
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: indavarapuA
    github:  indavarapuaneesh

# header_pages:
#   - about.md

# Build settings
plugins:
 - jekyll-feed
 - jekyll-seo-tag
